name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2025-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add repository to git safe directories
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./build
            ./.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle.lockfile') }}
          restore-keys: |
            gradle-${{ runner.os }}
            gradle-

      - name: Run Spotless Check
        if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/master' }}
        run: ./gradlew spotlessCheck

      - name: Build and Test
        run: ./gradlew build
